language: php

jobs:
  include:
    - php: 8.0
      dist: focal
    - php: 8.1
      dist: focal
    - php: 8.1
      dist: focal
      env: dependencies=lowest
    - php: 8.2
      dist: focal
    - php: 8.2
      dist: focal
      env: dependencies=lowest

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source
  - if [ "$dependencies" = "lowest" ]; then rm -rf vendor; composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
